version: "3"
services:
  submit:
    build: .
    image: slurm
    hostname: submit
    container_name: submit
    volumes:
      - ${PWD}/slurm.conf:/etc/slurm/slurm.conf
      - ${PWD}/share:/share
    command: >
        bash -c "sudo -u munge /usr/sbin/munged
        && slurmctld -D -i"
  compute0:
    build: .
    image: slurm
    hostname: compute0
    container_name: compute0
    volumes:
      - ${PWD}/slurm.conf:/etc/slurm/slurm.conf
      - ${PWD}/share:/share
    command: >
        bash -c "sudo -u munge /usr/sbin/munged
        && slurmd -D"
    depends_on:
      - "submit"
  compute1:
    build: .
    image: slurm
    hostname: compute1
    container_name: compute1
    volumes:
      - ${PWD}/slurm.conf:/etc/slurm/slurm.conf
      - ${PWD}/share:/share
    command: >
        bash -c "sudo -u munge /usr/sbin/munged
        && slurmd -D"
    depends_on:
      - "submit"
